# Generated by Django 5.0.4 on 2024-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=250, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
